[project]
name = "up-timer-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.15"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
up-timer-django = "up_timer_django:main"
[tool.ruff]
line-length = 88
target-version = "py315"
preview = true

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # import sorting
]
[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]
