# Generated by Django 6.1.1 on 2026-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("checking", "Checking"),
                    ("up", "Up"),
                    ("down", "Down"),
                    ("paused", "Paused"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="next_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
